# =========================
# App & Server
# =========================
spring.application.name=Medina-Asociados
server.port=4040
turno.precio.base=1500.00
# =========================
# Base de datos (Postgres)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/bbddMedinaAsoc
spring.datasource.username=admin
spring.datasource.password=porsche911GT3RS
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# =========================
# Mailtrap (Sandbox SMTP)
# =========================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=bb722d4df4868b
spring.mail.password=58952159d70d6f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
