# =========================
# App & Server
# =========================
spring.application.name=Medina-Asociados
server.port=${SERVER_PORT:8081}
spring.dotenv.location=file:.env
turno.precio.base=${TURNO_PRECIO_BASE:5000}

# =========================
# Base de datos (Postgres)
# =========================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# =========================
# Mailtrap (Sandbox SMTP)
# =========================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =========================
# Mercado Pago
# =========================
mp.access-token=${MP_ACCESS_TOKEN}
mp.notification-url=${MP_NOTIFICATION_URL}
mp.back-url.success=${MP_BACK_URL_SUCCESS}
mp.back-url.failure=${MP_BACK_URL_FAILURE}
mp.back-url.pending=${MP_BACK_URL_PENDING}