spring.application.name=Medina-Asociados
server.port=4040

spring.datasource.url=jdbc:postgresql://localhost:5432/bbddMedinaAsoc
spring.datasource.username=admin
spring.datasource.password=porsche911GT3RS

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update