@startuml derMedinaYAsociados
hide circle
hide empty method

entity Turno {
    -nroTurno <<PK>>: SERIAL
    -fechaHoraInicio: DATE
    -fechaHoraFin: DATE
    -observaciones: VARCHAR
    -importeTotal: INTEGER
    -cambioEstado <<FK>>: INTEGER
    -especialidad <<FK>>: INTEGER
    -cobro <<FK>>: INTEGER
    -estadoActual <<FK>>: INTEGER
}

entity Abogado {
    -matricula <<PK>>: VARCHAR
    -nombre: VARCHAR
    -apellido: VARCHAR
    -dni: INTEGER
    -direccion: VARCHAR
    -telefono: INTEGER
    -email: VARCHAR
}

entity Cliente {
    -idCliente: <<PK>> SERIAL
    -nombre: VARCHAR
    -apellido: VARCHAR
    -dni: INTEGER
    -direccion: VARCHAR
    -telefono: INTEGER
    -email: VARCHAR
}

entity Cobro {
    -fechaCobro: DATE
    -importeTotal: INTEGER
    -estadoCobro <<FK>>: INTEGER
}

entity Especialidad {
    -idEspecilidad <<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}

entity TipoCobro {
    -idTipoCobro <<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}

entity Estado {
    -idEstado <<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}

entity DetalleCobro {
    - idDetalleCobro <<PK>> : SERIAL
    - idCobro <<FK>> : INTEGER
    - fecha : DATE
    - descripcion : VARCHAR
    - monto : DECIMAL
}

entity Direccion {
    -idDireccion <<PK>>: SERIAL
    -calle: VARCHAR
    -numero: INTEGER
    -piso: INTEGER
    -departamento: VARCHAR
    -localidad <<FK>>: INTEGER
    -provincia: VARCHAR
    -codigoPostal: INTEGER
}

entity Localidad {
    -idLocalidad <<PK>>: SERIAL
    -nombre: VARCHAR
    -codigoPostal: INTEGER
}

entity HorarioTurno {
    -idHorarioTurno <<PK>>: SERIAL
    -idTurno <<FK>>: INTEGER
    -fecha: DATE
    -horaInicio: TIME
    -horaFin: TIME
}

entity HistorialTurno {
    -idHistorialTurno <<PK>>: SERIAL
    -idTurno <<FK>>: INTEGER
    -fechaHoraInicio: DATE
    -fechaHoraFin: DATE
    -estadoHistorial <<FK>>: INTEGER
}

entity AbogadoXEspecialidad{
    -idAbogado <<FK>>: INTEGER
    -idEspecialidad <<FK>>: INTEGER
}

Turno ||--|| Cobro 
Turno }o--|| Estado : "estadoActual"
Turno ||--|{ HistorialTurno
Turno ||--|| Especialidad
Turno ||--|| HorarioTurno
Turno }o--|| Abogado

Cobro ||--o{ DetalleCobro
Cobro }o--|| Estado

Cliente ||--o{ Turno
Cliente }--|| Direccion


DetalleCobro }o--|| TipoCobro

HistorialTurno }o--||Estado

HorarioTurno }o--||Estado

AbogadoXEspecialidad }o-up-|| Especialidad
AbogadoXEspecialidad }o-up-|| Abogado

Direccion }o--|| Localidad

@enduml