@startuml derMedinaYAsociados
hide circle
hide empty method

entity Turno {
    -idTurno <<PK>>: SERIAL
    -fechaHoraInicio: DATE
    -fechaHoraFin: DATE
    -observaciones: VARCHAR
    -importeTotal: INTEGER
    -HistorialTurno <<FK>>: INTEGER
    -especialidad <<FK>>: INTEGER
    -cobro <<FK>>: INTEGER
    -estadoActual <<FK>>: INTEGER
    -usuario <<FK>>: INTEGER
}

entity Abogado {
    -idAbogado <<PK>>: SERIAL
    -matricula: VARCHAR
}


entity Cobro {
    -fechaCobro: DATE
    -importeTotal: INTEGER
    -estadoCobro <<FK>>: INTEGER
}

entity Especialidad {
    -idEspecilidad <<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}

entity TipoCobro {
    -idTipoCobro <<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}

entity Estado {
    -idEstado <<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}

entity DetalleCobro {
    - idDetalleCobro <<PK>> : SERIAL
    - idCobro <<FK>> : INTEGER
    - fecha : DATE
    - descripcion : VARCHAR
    - monto : DECIMAL
}

entity Direccion {
    -idDireccion <<PK>>: SERIAL
    -calle: VARCHAR
    -numero: INTEGER
    -piso: INTEGER
    -departamento: VARCHAR
    -localidad <<FK>>: INTEGER
    -provincia: VARCHAR
}

entity Localidad {
    -idLocalidad <<PK>>: SERIAL
    -nombre: VARCHAR
    -codigoPostal: INTEGER
}

entity HorarioTurno {
    -idHorarioTurno <<PK>>: SERIAL
    -idTurno <<FK>>: INTEGER
    -fechHoraInicio: TIME
}

entity HistorialTurno {
    -idHistorialTurno <<PK>>: SERIAL
    -idTurno <<FK>>: INTEGER
    -fechaHoraInicio: DATE
    -fechaHoraFin: DATE
    -estadoHistorial <<FK>>: INTEGER
}

entity AbogadoXEspecialidad{
    -idAbogadoXEspecialidad <<PK>>: SERIAL
    -idAbogado <<FK>>: INTEGER
    -idEspecialidad <<FK>>: INTEGER
}

entity Usuario{
    -idUsuario <<PK>>: SERIAL
    -nombre: VARCHAR
    -apellido: VARCHAR
    -dni: INTEGER
    -direccion: VARCHAR
    -telefono: INTEGER
    -email: VARCHAR
    -rol <<FK>>: INTEGER
    -abogado <<FK>>: INTEGER
    -direccion <<FK>>: INTEGER
}

entity Rol {
    -idRol <<PK>>: SERIAL
    -nombre
    -descripcion
}

entity Permiso{
    -idPermiso <<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}

entity RolxPermiso{
    -idRol <<FK>>: INTEGER
    -idPermiso <<FK>>: INTEGER
}

Turno ||--|| Cobro 
Turno }o--|| Estado : "estadoActual"
Turno ||--|{ HistorialTurno
Turno ||--|| Especialidad
Turno ||--|| HorarioTurno
Turno }o--|| Abogado

Cobro ||--o{ DetalleCobro
Cobro }o--|| Estado

DetalleCobro }o--|| TipoCobro

HistorialTurno }o--||Estado

HorarioTurno }o--||Estado

AbogadoXEspecialidad }o-up-|| Especialidad
AbogadoXEspecialidad }o-up-|| Abogado

Direccion }o--|| Localidad

Usuario ||--|| Direccion
Usuario ||--|{ Turno

Usuario }|--|| Rol
RolxPermiso }|--|| Permiso
RolxPermiso }|--|| Rol
@enduml