@startuml Diagrama de Clases
class Turno {
    - idTurno
    - estadoActual:Estado
    - ultimoHistorialTurno:HistorialTurno
    - especialidad: Especialidad
    - cobro:Cobro
    - horario: HorarioTurno
    - usuario: Usuario
    - observaciones
    + crear()
    + modificar()
}
Turno --> "1..* "Cobro
Turno -> "1" Estado
Turno -->"1..*" HistorialTurno
Turno --> "1" Especialidad
Turno -left-> "1"HorarioTurno
Turno ..> "1..*"Usuario

class Especialidad {
    - nombre
    - descripcion
    + crear()
    + mostrar()
}

class Usuario{
    - nombre
    - apellido
    - dni
    - direccion:Direccion
    - telefono
    - email
    - rol: Rol
    - contraseña
    - turnos: Turno
    + crear()
    + mostrar()
}

Usuario -->"1" Direccion
Usuario -->"1" Rol
Usuario -->"1..*" Turno

class Rol{
    - nombre
    - descripcion
    + crear()
    + mostrar()
}

Rol--> "1..*" Permisos

class Permisos {
    - nombre
    - descripcion
    + crear()
    + mostrar()
}

class Abogado {
    - matricula
    - especialidad: Especialidad
    - usuario: Usuario
    + crear()
    + mostrar()
}

Abogado -->"1..*" Especialidad
Abogado -->"1"Usuario

class HistorialTurno{
    - fechaHoraInicio
    - fechaHoraFin
    + crear()
    + mostrar()
}

HistorialTurno -->"1" Estado

class Cobro {
    - fechaHoraCobro
    - importeTotal
    - estado:Estado
    - detalleCobro:DetalleCobro
    + calcularSaldoPendiente()
    + calcularImporteTotal()
    + crear()
    + mostrar()

}

Cobro o--"1..*" DetalleCobro
Cobro -->"1" Estado

class DetalleCobro {
    - fecha
    - descripcion
    - monto
    - tipoCobro: TipoCobro
    + crear()
    + mostrar()
}

DetalleCobro --> "1" TipoCobro

class TipoCobro {
    - nombre
    - descripcion
    + crear()
    + mostrar()
}

class Estado{
    - ambito
    - valor
    + crear()
    + mostrar()
    + setValor(valor)
    + setAmbito(ambito)
    + getValor()
    + getAmbito()
}

note bottom of Estado : Los metodos de seteo \nse encuentran en esta clase \ny son extensibles a las demas clases

class Direccion{
    - calle
    - numero
    - piso
    - departamento
    - localidad:Localidad
    - provincia
    + crear()
    + mostrar()
}

Direccion -->"1" Localidad

class Localidad{
    - nombre
    - codigoPostal
    + crear()
    + mostrar()
}

class HorarioTurno {
    - hora
    - fecha
    - estado
    - fechaHoraInicio
    - fechaHoraFin
    + crear()
    + mostrar()
}
note top of HorarioTurno : La fecha podria ir en \nesta clase o en la clase Turno
note bottom of HorarioTurno: La duracion del turno \nes de 45 minutos

HorarioTurno --> "1"Estado
@enduml