@startuml CasoUsoTurnos

left to right direction
actor Cliente
actor Abogado
actor "Usuario Turno" as UT
actor Usuario
actor "Administrador" as Admin


Cliente --> (1. Registrar turno)

Cliente --> (11. Pagar turno)
Cliente --|> UT

Usuario --> (4. Consultar perfil)
Usuario --> (19. Registrar perfil)
Usuario --> (20. Iniciar Sesion)
UT --|> Usuario
UT --> (2. Cancelar turno)
UT --> (3. Consultar turnos)
UT --> (5. Reprogramar turno)

(3. Consultar turnos) <.. (7. Consultar Detalle Turno): <<ext>>
(7. Consultar Detalle Turno) <.. (8. Consultar Historial Turno): <<ext>>

Abogado --|> UT
Abogado --> (6. Registrar Turno Offline)
(6. Registrar Turno Offline) ..> (16. Registrar Usuario Offline): <<include>>
Abogado --> (12. Marcar Turno en Curso)
Abogado --> (13. Finalizar Turno)
Abogado --> (14. Marcar como No Asistio)
Abogado --> (15. Marcar Turno como Pagado)
Abogado --> (19. Buscar Cliente)

Admin --|> Usuario
Admin --> (9. Registrar Abogado)
Admin --> (10. Modificar Abogado)
Admin --> (17. Consultar Precio de Turnos)
Admin --> (18. Modificar Precio de Turnos)


@enduml
